In [1]:
import gzip

import numpy as np
import pandas as pd
from tqdm.auto import tqdm

In [2]:
i5_string = """TAGATCGC
CTCTCTAT
TATCCTCT
AGAGTAGA
GTAAGGAG
ACTGCATA
AAGGAGTA
CTAAGCCT
GGCTACTC
CCTCAGAC
TCCTTACG
ACGCGTGG
GGAACTCC
TGGCCATG
GAGAGATT
CGCGGTTA
GACCGCCA
TAAGATGG
ATTGACAT
AGCCAACT
TACTAGGT
TCACGGTT
TGTAATGA
CACGTCAG
CTGAATTC
CGTACCGG
GATGACGG
TATAGACG
GTCATTGA
GCATCGTT
AGGTTGAC
TGAAACTG
"""
i5_name_string = """16Sf_501
16Sf_502
16Sf_503
16Sf_504
16Sf_505
16Sf_506
16Sf_507
16Sf_508
16Sf_509
16Sf_510
16Sf_511
16Sf_512
16Sf_513
16Sf_514
16Sf_515
16Sf_516
16Sf_517
16Sf_518
16Sf_519
16Sf_520
16Sf_521
16Sf_522
16Sf_523
16Sf_524
16Sf_525
16Sf_526
16Sf_527
16Sf_528
16Sf_529
16Sf_530
16Sf_531
16Sf_532
"""
i7_string = """TAAGGCGA
CGTACTAG
AGGCAGAA
TCCTGAGC
GGACTCCT
TAGGCATG
CTCTCTAC
CAGAGAGG
GCTACGCT
CGAGGCTG
AAGAGGCA
GTAGAGGA
ATTGTAAT
GATCATTC
ACCGATCG
CCGTTATT
TTCTTCTA
TACCTGAC
AGGACCGC
GTCCGATT
CACGAGTT
CCACGGCC
ACATGTAA
TGTTAACT
CAGTATCG
CGTCTCTA
AGATGCCT
GATTCTGC
TTAGCGAG
GTCCATGT
GCTCACAT
CGTTGAAC
GTCATGCT
TGGCTTAC
CCGTATGT
TCTGGAGA
AGGTCTAC
TCCGTACT
GCGAACTA
TCCGAATC
AGGTCAGT
AAGTGCTC
GTAAGCAG
ATGACGGT
TGAGAGCA
TCTGGTAC
CGAATTGG
ACATGACC
"""
i7_name_string = """16Sr_701
16Sr_702
16Sr_703
16Sr_704
16Sr_705
16Sr_706
16Sr_707
16Sr_708
16Sr_709
16Sr_710
16Sr_711
16Sr_712
16Sr_713
16Sr_714
16Sr_715
16Sr_716
16Sr_717
16Sr_718
16Sr_719
16Sr_720
16Sr_721
16Sr_722
16Sr_723
16Sr_724
16Sr_725
16Sr_726
16Sr_727
16Sr_728
16Sr_729
16Sr_730
16Sr_731
16Sr_732
16Sr_733
16Sr_734
16Sr_735
16Sr_736
16Sr_737
16Sr_738
16Sr_739
16Sr_740
16Sr_741
16Sr_742
16Sr_743
16Sr_744
16Sr_745
16Sr_746
16Sr_747
16Sr_748
"""

In [3]:
def get_i5_i7_from_fastq(fastq_path: str) -> tuple[list[str], list[str], list[str]]:
    f = gzip.open(fastq_path, "rb") if fastq_path.endswith(".gz") else open(fastq_path)
    i7_list, i5_list, ix_list = [], [], []
    for line in tqdm(f):
        line = line.decode() if fastq_path.endswith(".gz") else line
        if line.startswith("@M00312"):
            i7_i5 = line.strip().split(":")[-1]
            try:
                i7, i5 = i7_i5.split("+")
            except ValueError:
                ix_list.append(i7_i5)
                continue
            i7_list.append(i7)
            i5_list.append(i5)
    f.close()
    return i7_list, i5_list, ix_list

In [13]:
def get_i7_i5_idx(i7_list, i5_list) -> tuple[list[int], list[int]]:
    i7, i5 = pd.Series(i7_list), pd.Series(i5_list)

    i7_idxs = []
    i7_all = i7_string.split()
    # for i in i7.value_counts().to_frame().query("index.str.endswith('AT')").index:
    for i in i7.value_counts().to_frame().index:
        # i = i[:-2]
        try:
            idx = i7_all.index(i)
        except ValueError:
            idx = -1
        i7_idxs.append(idx)
    del idx
    
    i5_idxs = []
    i5_all = i5_string.split()
    # for i in i5.value_counts().to_frame().query("index.str.endswith('AC')").index:
    for i in i5.value_counts().to_frame().index:
        # i = i[:-2]
        try:
            idx = i5_all.index(i)
        except ValueError:
            idx = -1
        i5_idxs.append(idx)
    
    return i7_idxs, i5_idxs

In [11]:
i7_list, i5_list, ix_list = get_i5_i7_from_fastq("fastq/Undetermined_S0_L001_R1_001.fastq.gz")

0it [00:00, ?it/s]

In [15]:
i7_idxs, i5_idxs = get_i7_i5_idx(i7_list, i5_list)
print(len(i7_idxs), len(i5_idxs))
for i in i7_idxs:
    print(i7_name_string.split()[i] if i >= 0 else "U", end=" ")
print()
for i in i5_idxs:
    print(i5_name_string.split()[i] if i >= 0 else "U", end=" ")

33951 2145

In [23]:
i5_idxs[1]

'TCTTTCCC'

In [35]:
i7i5_list = [f"{i7}_{i5}" for i7, i5 in zip(i7_list, i5_list)]
index_df = pd.DataFrame({"i7_i5": i7i5_list, "i7": i7_list, "i5": i5_list})
vc = index_df["i7_i5"].value_counts()
index_df = index_df.drop_duplicates().reset_index(drop=True)
index_df["i7_i5_count"] = index_df["i7_i5"].map(vc)
index_df["i7_idx"] = index_df["i7"].apply(lambda x: {s: i for i, s in enumerate(i7_string.split())}.get(x, -1))
index_df["i5_idx"] = index_df["i5"].apply(lambda x: {s: i for i, s in enumerate(i5_string.split())}.get(x, -1))
index_df["i7_name"] = index_df["i7_idx"].apply(lambda x: i7_name_string.split()[x] if x >= 0 else "U")
index_df["i5_name"] = index_df["i5_idx"].apply(lambda x: i5_name_string.split()[x] if x >= 0 else "U")
index_df.sort_values("i7_i5_count", ascending=False).head(40)

,i7_i5,i7,i5,i7_i5_count,i7_idx,i5_idx,i7_name,i5_name
43101,CGTACTAG_ACGCGTGG,CGTACTAG,ACGCGTGG,184713,1,11,16Sr_702,16Sf_512
43105,CGTACTAG_CCTCAGAC,CGTACTAG,CCTCAGAC,131857,1,9,16Sr_702,16Sf_510
43106,CGTACTAG_GGAACTCC,CGTACTAG,GGAACTCC,99276,1,12,16Sr_702,16Sf_513
43102,CGTACTAG_TGGCCATG,CGTACTAG,TGGCCATG,63657,1,13,16Sr_702,16Sf_514
43104,AGGCAGAA_TGGCCATG,AGGCAGAA,TGGCCATG,63484,2,13,16Sr_703,16Sf_514
14,CGTACTAG_TCTTTCCC,CGTACTAG,TCTTTCCC,50464,1,-1,16Sr_702,U
43103,AGGCAGAA_GAGAGATT,AGGCAGAA,GAGAGATT,41265,2,14,16Sr_703,16Sf_515
43108,AGGCAGAA_GGAACTCC,AGGCAGAA,GGAACTCC,14632,2,12,16Sr_703,16Sf_513
43120,CGTACTAG_TCCTTACG,CGTACTAG,TCCTTACG,10396,1,10,16Sr_702,16Sf_511
31,AGGCAGAA_TCTTTCCC,AGGCAGAA,TCTTTCCC,7826,2,-1,16Sr_703,U
43126,AGGCAGAA_CCTCAGAC,AGGCAGAA,CCTCAGAC,6367,2,9,16Sr_703,16Sf_510
24,CGTACTAT_TCTTTCCC,CGTACTAT,TCTTTCCC,6044,-1,-1,U,U
13,CTTACTAG_TCTTTCCC,CTTACTAG,TCTTTCCC,5802,-1,-1,U,U
21,CGTACTCG_TCTTTCCC,CGTACTCG,TCTTTCCC,3550,-1,-1,U,U
2420,TTATTATT_TCTTTCCC,TTATTATT,TCTTTCCC,3126,-1,-1,U,U
782,TAATTATT_TCTTTCCC,TAATTATT,TCTTTCCC,2942,-1,-1,U,U
84,AGTACTAG_TCTTTCCC,AGTACTAG,TCTTTCCC,2256,-1,-1,U,U
19,CGTCCTAG_TCTTTCCC,CGTCCTAG,TCTTTCCC,2152,-1,-1,U,U
97,CTTACTAT_TCTTTCCC,CTTACTAT,TCTTTCCC,2134,-1,-1,U,U
91,CGTACTAA_TCTTTCCC,CGTACTAA,TCTTTCCC,2086,-1,-1,U,U
28,ATGCAGAA_TCTTTCCC,ATGCAGAA,TCTTTCCC,2030,-1,-1,U,U
66,CGTAATAG_TCTTTCCC,CGTAATAG,TCTTTCCC,1822,-1,-1,U,U
77,CGAACTAG_TCTTTCCC,CGAACTAG,TCTTTCCC,1808,-1,-1,U,U
824,CGTACTAG_GCGTGGTA,CGTACTAG,GCGTGGTA,1494,1,-1,16Sr_702,U
43165,CGTACTAG_GGGACTCC,CGTACTAG,GGGACTCC,1485,1,-1,16Sr_702,U
106,CATACTAG_TCTTTCCC,CATACTAG,TCTTTCCC,1470,-1,-1,U,U
4171,TTATTACT_TCTTTCCC,TTATTACT,TCTTTCCC,1406,-1,-1,U,U
1714,TAATTATA_TCTTTCCC,TAATTATA,TCTTTCCC,1398,-1,-1,U,U
1345,TTATTATA_TCTTTCCC,TTATTATA,TCTTTCCC,1348,-1,-1,U,U
43137,CGTACTAG_GGCTACTC,CGTACTAG,GGCTACTC,1332,1,8,16Sr_702,16Sf_509
3298,TAATAATT_TCTTTCCC,TAATAATT,TCTTTCCC,1304,-1,-1,U,U
663,TTATAATT_TCTTTCCC,TTATAATT,TCTTTCCC,1278,-1,-1,U,U
253,AAGCAGAA_TCTTTCCC,AAGCAGAA,TCTTTCCC,1234,-1,-1,U,U
273,AGGCAGCA_TCTTTCCC,AGGCAGCA,TCTTTCCC,1228,-1,-1,U,U
1142,AAATAATA_TCTTTCCC,AAATAATA,TCTTTCCC,1184,-1,-1,U,U
1658,CTTACTCG_TCTTTCCC,CTTACTCG,TCTTTCCC,1174,-1,-1,U,U
3041,TAATTACT_TCTTTCCC,TAATTACT,TCTTTCCC,1168,-1,-1,U,U
160,TAATAATA_TCTTTCCC,TAATAATA,TCTTTCCC,1154,-1,-1,U,U
1067,CGGACTAG_TCTTTCCC,CGGACTAG,TCTTTCCC,1104,-1,-1,U,U
226,AGGAAGAA_TCTTTCCC,AGGAAGAA,TCTTTCCC,1100,-1,-1,U,U

In [31]:
index_df

,i7_i5,i7,i5,i7_idx,i5_idx,i7_name,i5_name,i7_i5_count
886871,CGTACTAG_ACGCGTGG,CGTACTAG,ACGCGTGG,1,11,16Sr_702,16Sf_512,184713
685047,CGTACTAG_ACGCGTGG,CGTACTAG,ACGCGTGG,1,11,16Sr_702,16Sf_512,184713
685076,CGTACTAG_ACGCGTGG,CGTACTAG,ACGCGTGG,1,11,16Sr_702,16Sf_512,184713
685071,CGTACTAG_ACGCGTGG,CGTACTAG,ACGCGTGG,1,11,16Sr_702,16Sf_512,184713
685069,CGTACTAG_ACGCGTGG,CGTACTAG,ACGCGTGG,1,11,16Sr_702,16Sf_512,184713
...,...,...,...,...,...,...,...,...
1304644,CGGACTAG_GCCTTACG,CGGACTAG,GCCTTACG,-1,-1,U,U,1
884006,AGGCAGAG_GAGAGTTT,AGGCAGAG,GAGAGTTT,-1,-1,U,U,1
801153,CATACTAG_TGGCTATG,CATACTAG,TGGCTATG,-1,-1,U,U,1
769725,CGTCCTAG_AAGAGATT,CGTCCTAG,AAGAGATT,-1,-1,U,U,1
1028439,AGTCAGAA_TGGCCATT,AGTCAGAA,TGGCCATT,-1,-1,U,U,1

In [26]:
# i7_df = pd.Series(i7_list).to_frame().rename(columns={0: "i7"})
# i5_df = pd.Series(i5_list).to_frame().rename(columns={0: "i5"})
# i7s = i7_string.split()
# i5s = i5_string.split()
# i7_name_list = i7_name_string.split()
# i5_name_list = i5_name_string.split()
# i7_name_list.append("U")
# i5_name_list.append("U")
# i7_names = []
# i5_names = []
# i7_df["i7_name"] = i7_df.i7.apply(
#     lambda x: i7_name_list[i7s.index(x)] if x in i7s else "U"
# )
# i5_df["i5_name"] = i5_df.i5.apply(
#     lambda x: i5_name_list[i5s.index(x)] if x in i5s else "U"
# )
# for i7_idx in list(range(len(i7s))) + [-1]:
#     # get the most frequent i5 corresponding to this i7
#     # i7 = f"{i7s[i7_idx]}AT"
#     i7_name = f"{i7_name_list[i7_idx]}"
#     i7_df_sub = i7_df.query("i7_name == @i7_name")
#     if i7_df_sub.shape[0]:
#         i5_name = i5_df.loc[i7_df_sub.index.tolist()].i5_name.value_counts().index[0]
#         i7_names.append(i7_name)
#         # i5_names.append(i5_name_string.split()[i5s.index(i5[:-2])])
#         i5_names.append(i5_name)
# idx = np.argsort(i7_names)
# i7_names = np.array(i7_names)[idx]
# i5_names = np.array(i5_names)[idx]
# for i7, i5 in zip(i7_names, i5_names):
#     print(i7, i5)

16Sr_701 U
16Sr_702 16Sf_512
16Sr_703 16Sf_514
16Sr_704 16Sf_512
16Sr_705 U
16Sr_706 U
16Sr_707 U
16Sr_708 U
16Sr_711 U
16Sr_712 U
16Sr_713 U
16Sr_715 16Sf_513
16Sr_716 U
16Sr_717 U
16Sr_718 U
16Sr_720 U
16Sr_723 U
16Sr_724 U
16Sr_725 U
16Sr_726 U
16Sr_728 U
16Sr_729 U
16Sr_733 U
16Sr_736 U
16Sr_737 U
16Sr_738 U
16Sr_739 U
16Sr_740 U
16Sr_742 U
16Sr_743 U
16Sr_747 U
16Sr_748 U
U U